Another/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogListView.as_view(), name = 'index'),
    path('detail/<int:pk>', views.blogDetialView.as_view(), name = 'detail'),
    path('registe', views.registe, name = 'registe'),
    path('login', views.login, name = 'login'),
    path('logout', views.logout, name = 'logout'),
    path('pblog', views.pblog, name = 'pblog'),
    path('comment/<int:tid>', views.comment, name = 'comment'),
    path('home/<int:pk>', views.blogerDetailView.as_view(), name = 'home'),
]

blog/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Attention(models.Model):
    aid = models.AutoField(db_column='Aid', primary_key=True)  # Field name made lowercase.
    uid = models.ForeignKey('Bloger', models.DO_NOTHING, db_column='Uid', related_name = 'attenuid')  # Field name made lowercase.
    touid = models.ForeignKey('Bloger', models.DO_NOTHING, db_column='ToUid')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Attention'


class Blog(models.Model):
    tid = models.AutoField(db_column='Tid', primary_key=True)  # Field name made lowercase.
    uid = models.ForeignKey('Bloger', models.DO_NOTHING, db_column='Uid')  # Field name made lowercase.
    date = models.DateTimeField(blank=True, null=True)
    content = models.TextField(db_column='Content', blank=True, null=True)  # Field name made lowercase.
    title = models.TextField(db_column='Title', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Blog'


class Bloger(models.Model):
    uid = models.AutoField(db_column='Uid', primary_key=True)  # Field name made lowercase.
    uname = models.CharField(db_column='Uname', unique=True, max_length=20)  # Field name made lowercase.
    upass = models.CharField(db_column='Upass', max_length=20)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Bloger'


class Comment(models.Model):
    tid = models.AutoField(db_column='Tid', primary_key=True)  # Field name made lowercase.
    uid = models.ForeignKey(Bloger, models.DO_NOTHING, db_column='Uid')  # Field name made lowercase.
    cid = models.IntegerField(db_column='Cid', blank=True, null=True)  # Field name made lowercase.
    date = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(db_column='Comment', blank=True, null=True)  # Field name made lowercase.
    type = models.TextField(db_column='Type', blank=True, null=True)  # Field name made lowercase. This field type is a guess.

    class Meta:
        managed = False
        db_table = 'Comment'


class Gath(models.Model):
    tid = models.IntegerField(db_column='Tid', primary_key=True)  # Field name made lowercase.
    uid = models.IntegerField(db_column='Uid')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Gath'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .froms import UserForm
from .models import Bloger, Blog, Gath, Comment

# Create your views here.
class blogListView(ListView):
    model = Blog
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(blogListView, self).get_context_data(**kwargs)
        return context

class blogDetialView(DetailView):
    model = Gath
    template_name = 'blog_detail.html'

    def get_object(self):
        object = super(blogDetialView, self).get_object()
        object = Blog.objects.get(tid = object.tid)
        return object

    def get_context_data(self, **kwargs):
        context = super(blogDetialView, self).get_context_data(**kwargs)
        context['Comment'] = Comment.objects.all()
        return context
class blogerDetailView(DetailView):
    model = Bloger
    template_name = 'bloger_detail.html'

def index(request):

    return render(request, 'index.html')

def registe(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            uf.save()
            return HttpResponse('registe successfuly')
    uf = UserForm()
    return render(request, 'registe.html', {'form':uf, 'action':'Registe'})

def login(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            bloger = uf.save(commit=False)
            try:
                dbloger = Bloger.objects.get(uname=bloger.uname)
                if dbloger.upass == bloger.upass:
                    request.session['id'] = dbloger.uid
                    return HttpResponse("OK")
                else:
                    return HttpResponse(bloger.upass)
            except:
                return HttpResponse("FAILER")
        else:
            return HttpResponse("404")

    uf = UserForm()
    return render(request, 'registe.html', {'form':uf, 'action':'Login'})

def logout(request):
    request.session.pop('id')
    return HttpResponse('Logout Ok')

def pblog(request):
    if request.method == 'POST':
        blog = Blog()
        blog.content = request.POST['content']
        blog.title = request.POST['title']
        blog.uid = Bloger.objects.get(uid = request.session['id'])
        blog.date = timezone.now()
        blog.save()
        return HttpResponse("Post Successfully")
    try:
        request.session['id']
        return render(request, 'pblog.html')
    except:
        return HttpResponse('Login First')

def comment(request, **tid):
    if request.method == 'POST':
        bid = request.META['HTTP_REFERER'].split('/')[-1]
        comment = Comment()
        comment.comment = request.POST['comment']
        comment.cid = Gath.objects.get(tid = bid)
        comment.date = timezone.now()
        comment.uid = Bloger.objects.get(uid = request.session['id'])
        comment.save()
        return HttpResponse("Comment OK")
    return HttpResponse(tid['tid'])

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Diy Bolg</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    .col-sm-2{
      float: left;
      width: 22%;
    }
    .col-sm-10{
      float: right;
      width: 78%;
    }
    a{ 
      text-decoration: none;
      padding-left: 5%;
      padding-bottom: 5%;
      font-size: 20px;
      color: green
    }
    {% block css%}{% endblock %}
  </style>
  

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">
    
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href={% url 'home' request.session.id %}>Home</a></li>
          <li><a href="">All blogs</a></li>
          <li><a href="">All blogers</a></li>
      </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

blog/templates/blog_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>blog Detail</title>
    <style>
        #id_comment{
            width: 100%
        }
        #comment_attr{
            float: right;
            color:brown;
        }
        .bor{
            margin-bottom: 10%;
        }
        input{
            width: 30%;
            padding-bottom: 1%;
            padding-top: 1%;
            float: right;
            background: wheat;
            border: white;
        }
        a{
            text-decoration: none;
            padding-left: 5%;
            padding-bottom: 5%;
        }

    </style>
</head>
<body>
    <p><strong>Author:</strong><a href="">{{ object.uid.uname }}</a></p>
    <p><strong>Title:</strong><a href="">{{ object.title }}</a></p>
    <p><strong>Date:</strong><a href="">{{ object.date }}</a></p>
    <p>{{ object.content }}</p>
    <div class="bor">
        <form action="../comment" method="post">{% csrf_token %}
            <label for="id_content">Comment:</label>
            <textarea name="comment" cols="40" rows="10" class="vLargeTextField" id="id_comment"></textarea>
            <input type="submit" value="Post it"/>
        </form>
    </div>
    <p>{% for comment in Comment %}
        {% if comment.cid == object.tid %}
        <li>{{comment.comment}}</li>
        <div id="comment_attr">
            <p><strong>{{comment.date}}</strong> by <strong>{{comment.uid.uname}}</strong></p>
            <a href={% url 'comment' comment.tid %}>comment it</a>
        </div>
        {% endif %}
    {% endfor %}</p>
</body>
</html>

blog/templates/bloger_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Personal Home</title>
    <style>
        .pdiv{
            margin-left: 10%;
            position: absolute;
            top: 30%;
            left: 30%;
        }
        a{
            text-decoration: none;
            padding-left: 5%;
            padding-bottom: 5%;
        }
        .val{
            float: right;
            width: 15%;
        }
    </style>
</head>
<body>
    <div class="pdiv">
        <p><strong>My NickName:</strong><span class="val">{{object.uname}}</span></p>
        <p><strong>My Description:</strong><span class="val">{{object.description}}</span></p>
        <a href="">Edit Description</a>
    </div>

</body>
</html>

blog/templates/index.html
{% extends "base_generic.html" %}

{% block css %}
  .index{
    float:right;
    width:40%
  }
  ul{
    color:orange;
  }
{% endblock %}

{% block content %}
<br>
<h1>Diy Blog</h1>

  <p>Welcome to <em>Diy Blog</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The blog has the following latest posts:</p>
  <!-- <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul> -->
  <ul>
    {% for blog in blog_list %}
    <li>
      <a href={% url 'detail' blog.tid %}>{{ blog.title }}</a>
    </li>
    {% endfor %}
  </ul>
  <br>
  <div class="index">
    <a href={% url 'registe' %}>registe</a>
    <a href={% url 'login' %}>login</a>
    <a href={% url 'logout' %}>logout</a>
    <a href={% url 'pblog' %}>post a blog</a>
  </div>

{% endblock %}

blog/templates/pblog.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
</head>
<body>      
    <form method="POST">{% csrf_token %}
        <div>
            <label for="id_content">Title:</label>
            <textarea name="title" cols="20" rows="1" class="vLargeTextField" id="id_content"></textarea>
            <label for="id_content">Content:</label>
            <textarea name="content" cols="40" rows="10" class="vLargeTextField" id="id_content"></textarea>
        </div>
        <input type="submit" value="Post it"/>
    </form>
</body>
</html>

blog/templates/registe.html
<!DOCTYPE html>
<html>
<head>
    <style>
        button{
            margin-top: 20%;
            height: 20%;/*长宽应该要按照自己的代码设置，此处外层有嵌套，所以用百分比*/
            width: 100%;
            border-radius: 10px;
            border: 1px solid black;
            text-align: center;
            background:rgba(255, 251, 240, 0.3); /*R G B opacity*/
        }
        form{
            color:aqua;
            position: absolute;
            top: 30%;
            left: 40%;
            font-size: 20px;
        }
        input{
            float: right;
            width: 50%;
            border: 1px solid black;
            background:rgba(255, 251, 240, 0.3); /*R G B opacity*/
        }
        </style>
</head>
<body>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">{{ action }}</button>
    </form>
</body>
</html>